# Generated by Django 4.0 on 2021-12-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, null=True, verbose_name='Brand Name')),
                ('model_name', models.CharField(max_length=200, null=True, verbose_name='Model')),
                ('display', models.CharField(max_length=200, null=True, verbose_name='Display')),
                ('ram', models.CharField(max_length=200, null=True, verbose_name='Ram')),
                ('storage', models.CharField(max_length=200, null=True, verbose_name='Storage')),
                ('battry', models.CharField(max_length=200, null=True, verbose_name='Battery')),
                ('os', models.CharField(max_length=200, null=True, verbose_name='Operating System')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Price')),
                ('date_entry', models.DateTimeField(verbose_name='Date Entry')),
            ],
            options={
                'verbose_name': 'Product List',
                'verbose_name_plural': 'Product Lists',
            },
        ),
    ]
